import type { Metadata } from "next";
import BackToTop from "@/components/BackToTop";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
	title: "Search results for | InCoderWeb",
	description: "Generated by create next app",
};

export default function searchLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<>
      <Navbar/>
			{children}
			<BackToTop />
      <Footer/>
		</>
	);
}
